In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [2]:
url = 'https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=data/avia_par_pl.tsv.gz&unzip=true'

In [4]:
routes = pd.read_csv(url,delimiter='\t')

In [5]:
routes.head()

,"unit,tra_meas,airp_pr\time",2020Q3,2020Q2,2020Q1,2020M09,2020M08,2020M07,2020M06,2020M05,2020M04,...,2004M09,2004M08,2004M07,2004M06,2004M05,2004M04,2004M03,2004M02,2004M01,2004
0,"FLIGHT,CAF_PAS,PL_EPBY_BG_LBBG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
1,"FLIGHT,CAF_PAS,PL_EPBY_DE_EDDF",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
2,"FLIGHT,CAF_PAS,PL_EPBY_DE_EDLV",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
3,"FLIGHT,CAF_PAS,PL_EPBY_ES_LEGE",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
4,"FLIGHT,CAF_PAS,PL_EPBY_IE_EIDW",50,:,62,16,18,16,:,:,:,...,:,:,:,:,:,:,:,:,:,:

In [9]:
routesDesc=routes['unit,tra_meas,airp_pr\\time'].str.split(",",expand=True)

In [11]:
routesDesc.rename({0:"unit",1:"tra_meas",2:"airport"},axis="columns",inplace=True)

In [12]:
routesDesc.head()

     unit tra_meas          airport
0  FLIGHT  CAF_PAS  PL_EPBY_BG_LBBG
1  FLIGHT  CAF_PAS  PL_EPBY_DE_EDDF
2  FLIGHT  CAF_PAS  PL_EPBY_DE_EDLV
3  FLIGHT  CAF_PAS  PL_EPBY_ES_LEGE
4  FLIGHT  CAF_PAS  PL_EPBY_IE_EIDW

In [14]:
routesDesc=routesDesc.join(routes)

In [15]:
routesDesc.drop("unit,tra_meas,airp_pr\\time",axis=1,inplace=True)

In [16]:
routesDesc.head()

,unit,tra_meas,airport,2020Q3,2020Q2,2020Q1,2020M09,2020M08,2020M07,2020M06,...,2004M09,2004M08,2004M07,2004M06,2004M05,2004M04,2004M03,2004M02,2004M01,2004
0,FLIGHT,CAF_PAS,PL_EPBY_BG_LBBG,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
1,FLIGHT,CAF_PAS,PL_EPBY_DE_EDDF,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
2,FLIGHT,CAF_PAS,PL_EPBY_DE_EDLV,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
3,FLIGHT,CAF_PAS,PL_EPBY_ES_LEGE,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
4,FLIGHT,CAF_PAS,PL_EPBY_IE_EIDW,50,:,62,16,18,16,:,...,:,:,:,:,:,:,:,:,:,:

In [ ]:
pd.read_